# Generated by Django 6.0.5 on 2026-05-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_news_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
