# Generated by Django 6.0.5 on 2026-05-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_news_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='slug',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
