# Generated by Django 6.0.5 on 2026-05-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_projects_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageproject',
            name='image',
            field=models.ImageField(upload_to='other/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='MainImage',
            field=models.ImageField(upload_to='project/'),
        ),
    ]
