# Generated by Django 6.0.5 on 2026-05-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_imageproject_image_alter_projects_mainimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NameOne', models.CharField()),
                ('NameTwo', models.CharField()),
                ('Email', models.EmailField(max_length=254)),
                ('Text', models.TextField()),
            ],
            options={
                'verbose_name': 'Письмо',
                'verbose_name_plural': 'Письма',
            },
        ),
    ]
