# Generated by Django 6.0.5 on 2026-05-24 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_letter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Letter',
        ),
    ]
